name: AxSellwands
version: '${project.version}'
main: com.artillexstudios.axsellwands.AxSellwands
api-version: '1.20'
folia-supported: true

softdepend:
  - Vault
  - EconomyShopGUI
  - EconomyShopGUI-Premium
  - WorldGuard
